# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_window_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ChooseWinner(QtWidgets.QMainWindow):
    def __init__(self, team1, team2, callback):
        self.team1 = team1
        self.team2 = team2
        self.callback = callback

        super().__init__()
        self.setupUi(self)

    def on_click(self, team):
        self.close()
        self.callback(team)

    def setupUi(self, choose_winner):
        choose_winner.setObjectName("choose_winner")
        choose_winner.setFixedSize(600, 200)
        self.centralwidget = QtWidgets.QWidget(choose_winner)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonLeftTeam = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLeftTeam.setGeometry(QtCore.QRect(40, 50, 240, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonLeftTeam.setFont(font)
        self.pushButtonLeftTeam.setObjectName("pushButtonLeftTeam")
        self.pushButtonLeftTeam.setText(self.team1)
        self.pushButtonLeftTeam.clicked.connect(lambda: self.on_click(self.team1))
        self.pushButtonRightTeam = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRightTeam.setGeometry(QtCore.QRect(320, 50, 240, 50))
        self.pushButtonRightTeam.setFont(font)
        self.pushButtonRightTeam.setObjectName("pushButtonRightTeam")
        self.pushButtonRightTeam.setText(self.team2)
        self.pushButtonRightTeam.clicked.connect(lambda: self.on_click(self.team2))
        choose_winner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(choose_winner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        choose_winner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(choose_winner)
        self.statusbar.setObjectName("statusbar")
        choose_winner.setStatusBar(self.statusbar)

        self.retranslateUi(choose_winner)
        QtCore.QMetaObject.connectSlotsByName(choose_winner)

    def retranslateUi(self, choose_winner):
        _translate = QtCore.QCoreApplication.translate
        choose_winner.setWindowTitle(_translate("choose_winner", "Выберите победителя"))
