# -*- coding: utf-8 -*-
import random
import sys
from math import log2

# Form implementation generated from reading ui file 'enter_teams_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from main import MainWindow


class EnterTeamsWindow(QtWidgets.QMainWindow):
    def __init__(self, number_of_teams):
        super().__init__()
        self.number_of_teams = number_of_teams
        self.lineEdit_list = []
        self.window_width = 50 * self.number_of_teams
        self.setupUi(self)

    def get_text(self, lineEdit):
        text = lineEdit.text()
        if text == "":
            raise Exception("Заполните все поля")

        return text

    def open_main_window(self):
        # print(self.lineEdit_list[0].text())
        teams = []
        try:
            teams = list(map(lambda lineEdit: self.get_text(lineEdit), self.lineEdit_list))
        except Exception as e:
            QMessageBox.about(self, "Ошибка", str(e))
            print(Exception)
            return

        random.shuffle(teams)
        self.w = MainWindow(self.number_of_teams, teams)
        self.w.show()
        self.hide()

        # self.source_line_edit.selectAll()
        # self.source_line_edit.copy()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(self.window_width, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(self.window_width - 280, 500, 240 + 20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("Создать таблицу")
        self.pushButton.clicked.connect(self.open_main_window)

        x = 20
        y = 0

        for i in range(self.number_of_teams):
            label = QtWidgets.QLabel(self.centralwidget)
            label.setGeometry(QtCore.QRect(x, y, 140, 30))
            font = QtGui.QFont()
            font.setPointSize(10)
            label.setFont(font)
            # label.setObjectName("label")
            label.setText(f"Команда {i + 1}")

            y += 30

            self.lineEdit_list.append(QtWidgets.QLineEdit(self.centralwidget))
            self.lineEdit_list[i].setGeometry(QtCore.QRect(x, y, 140, 40))
            # self.lineEdit_list[i].textChanged.connect(lambda : print(1))
            self.lineEdit_list[i].text()
            font = QtGui.QFont()
            font.setPointSize(15)
            self.lineEdit_list[i].setFont(font)
            # self.lineEdit_list[i].setObjectName("lineEdit")
            y += 40 + 40
            if y >= 400:
                x += 140 + 26
                y = 0
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
# "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
# "p, li { white-space: pre-wrap; }\n"
# "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
# "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">wefwfsdf</p></body></html>"))
#
        # self.lineEdit.setText(_translate("MainWindow", "wrwerwerwer"))


#
# app = QtWidgets.QApplication([])
# application = EnterTeamsWindow(16)
# application.show()
#
# sys.exit(app.exec())