# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'menu_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from enter_teams import EnterTeamsWindow
from main import MainWindow


class MenuWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(400, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 300, 500))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.open_main_window)
        self.verticalLayout.addWidget(self.pushButton_8)

        self.pushButton_16 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.clicked.connect(self.open_main_window)
        self.verticalLayout.addWidget(self.pushButton_16)

        self.pushButton_32 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_32.clicked.connect(self.open_main_window)
        self.verticalLayout.addWidget(self.pushButton_32)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_8.setText(_translate("MainWindow", "8 команд"))
        self.pushButton_16.setText(_translate("MainWindow", "16 команд"))
        self.pushButton_32.setText(_translate("MainWindow", "32 команды"))

    def open_main_window(self):
        sender = self.sender()
        if sender == self.pushButton_8:
            self.w = EnterTeamsWindow(8)
            self.w.show()
            self.hide()
        elif sender == self.pushButton_16:
            self.w = EnterTeamsWindow(16)
            self.w.show()
            self.hide()
        elif sender == self.pushButton_32:
            self.w = EnterTeamsWindow(32)
            self.w.show()
            self.hide()
        else:
            print(2)
# class mywindow(QtWidgets.QMainWindow):


app = QtWidgets.QApplication([])
application = MenuWindow()
application.show()

sys.exit(app.exec())